version: '3.7'
services:
  database:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main_db
    ports:
      - '3306'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database
