show_data:
  path: /show/{date}
  controller: App\Controller\TransactionController::show
  methods: GET

import_data:
  path: /import/{date}
  controller: App\Controller\TransactionController::import
  methods: POST
