#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_data_show:
    path:       /show/{page}
    controller: App\Controller\TransactionController::show
    methods:    GET

api_data_import:
    path:       /show/{page}
    controller: App\Controller\TransactionController::import
    methods:    POST
