api_data_show:
  path: /show/{date}
  controller: App\Controller\TransactionController::show
  methods: GET

api_data_import:
  path: /import/{date}
  controller: App\Controller\TransactionController::import
  methods: POST
